language: python
python:
 - 3.6
 
addons:
  apt:
    update: true
    packages:
    - cmake
    - python3-dev python3-pip python3-tk python3-lxml python3-six
    
install:
 - pip3 install pytest
 - python3 setup.py bdist_wheel --GPU_build False
 - pip3 install ./dist/*.whl
 
script: 
 - python3 ./tests/pythontests.py
